### ISSUE TITLE
Documentation unclear on whether statsd-bridge requires statsd

### ISSUE THREAD

**Issue by ebpitts** [prometheus/statsd_bridge#15]
As I understand statsd's repeater mode, it forwards the unprocessed traffic it receives from statsd clients. This makes me think that instead of continuing to run statsd and having it repeat traffic to statsd-bridge, statsd-bridge can replace statsd and receive traffic directly from statsd client libraries. If this is correct, it would be nice to update the Overview section of the README to mention this style of usage.

**Comment by juliusv** [comment]
Good point. See my README.md PR here: https://github.com/prometheus/statsd_bridge/pull/16

**Comment by ebpitts** [comment]
Looks good. Thanks for the clarification!

**Comment by juliusv** [comment]
Cool, merged!
